#!/bin/bash

set -eo pipefail

# load env vars
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

function help() {
echo
echo "$1 <command> [options]"
echo
echo "commands:"
echo
column -t -s"|" ./task.md | tail -n +3
echo
}

case "$1" in
    install-tools)
        [ ! -d 'n' ] && curl -L https://git.io/n-install | bash
        [ ! -d '.pyenv' ] && git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        [ ! -d '.tmux' ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        sudo apt install -y zsh vim tmux jq pass
        ;;
    install-vim)
        vim -c ":PlugInstall"
        ;;
    install-zsh)
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        [ ! -d '.zsh/zsh-autosuggestions' ] && git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        cp .oh-my-zsh-custom/*.zsh .oh-my-zsh/custom
        ;;
    enable-passwordless-sudo)
        echo "$USERNAME ALL=(ALL) NOPASSWD: ALL"
        ;;
    *)
        help task
        exit 1
esac
