#!/bin/bash

set -eo pipefail

# load env vars
if [ -f .env ]
then
  export $(cat .env | sed 's/#.*//g' | xargs)
fi

function help() {
echo
echo "$1 <command> [options]"
echo
echo "commands:"
echo
column -t -s"|" ./task.md | tail -n +3
echo
}

case "$1" in
    install-docker)
        sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | sudo apt-key add - \
        && sudo apt-key fingerprint 0EBFCD88
        sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
        sudo apt-get update && sudo apt-get install docker-ce docker-ce-cli containerd.io
        sudo usermod -aG docker $USER
        ;;
    install-tools)
        cd ~
        [ ! -d 'n' ] && curl -L https://git.io/n-install | bash
        [ ! -d '.pyenv' ] && git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        [ ! -d '.tmux' ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        sudo apt install -y zsh vim tmux jq pass htop xclip ripgrep
        ;;
    install-vim)
        cp .vimrc ~/
        cd ~
        vim -c ":PlugInstall"
        ;;
    install-zsh)
        ZSH=
        rm -rf ~/.oh-my-zsh
        # Set zsh default
        ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
        cd ~
        # install oh-my-zsh
        curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
        # Clone zsh autosuggestions
        [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] && git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"
        # Copy oh-my-zsh customizations
        cp ~/dotfiles/oh-my-zsh-custom/*.zsh ~/.oh-my-zsh/custom
        # Clone z
        [ ! -d "$ZSH_CUSTOM/plugins/zsh-z" ] && git clone https://github.com/agkozak/zsh-z "$ZSH_CUSTOM/plugins/zsh-z"
        # Set plugins list for zshr
        sed -i'' 's/plugins=.*/plugins=(git fzf zsh-z ansible docker pyenv ripgrep)/g' ~/.zshrc
        ;;
    install-zsh-theme)
        # Clone and copy dracula theme
        [ ! -d 'zsh' ] && git clone https://github.com/dracula/zsh.git 
        ln -s ~/dotfiles/zsh/dracula.zsh-theme ~/.oh-my-zsh/themes/dracula.zsh-theme
        sed -i'' 's/ZSH_THEME.*/ZSH_THEME="dracula"/g' ~/.zshrc
        ;;
    enable-passwordless-sudo)
        echo "$USERNAME ALL=(ALL) NOPASSWD: ALL"
        ;;
    copy-dotfiles)
        cp .vimrc ~
        cp .tmux.conf ~
        cp .gitconfig ~
        ;;
    *)
        help task
        exit 1
esac
