#!/bin/bash

set -eo pipefail

# load env vars
if [ -f .env ]; then
    export $(cat .env | sed 's/#.*//g' | xargs)
fi

function help() {
    echo
    echo "$1 <command> [options]"
    echo
    echo "commands:"
    echo

cmd_width=24
opt_width=10
desc_width=60
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "Command" "Option" "Description"
echo "|$(printf '%*s' $((cmd_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((opt_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((desc_width + 2)) '' | tr ' ' '-')|"
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "activate-venv" "" "Source the Python venv with uv."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "enable-passwordless-sudo" "" "Get sudoers entry for passwordless sudo."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "init-venv" "" "Initialize the Python venv with uv."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-desktop" "" "Install desktop tools."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-bin" "" "Install binaries."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-rust" "" "Install Rust."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-python" "" "Install Python."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-exo" "" "Install Exoscale cli."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-node" "" "Install Node."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-docker" "" "Install Docker."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-podman" "" "Install podman."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-kind" "" "Install kubectl and kind."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-minikube" "" "Install kubectl and minikube."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-tmux" "" "Install tmux."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-vim" "" "Install vim and configure plugins."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-llm" "" "Intall LLM cli."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-ollama" "" "Intall Ollama cli."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-helix" "" "Install helix editor."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-helm" "" "Install Helm."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-nvim" "" "Install neovim and configure plugins."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-bash" "" "Configure bash."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-zsh" "" "Install zsh shell and oh-my-zsh."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-fish" "" "Install fish shell."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-qemu" "" "Install QUEMU."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-fzf" "" "Install fzf."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-git" "" "Configure git."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-pass" "" "Install and configure pass."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "install-scripts" "" "Install bash scripts."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "uninstall-docker" "" "Uninstall docker."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "run-open-webui" "" "Run Open WebUI."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "setup-mint-system" "" "Clone Mint System git repos."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "setup-steamdeck" "" "Setup steamdeck os."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "setup-sozialinfo" "" "Clone Sozialinfo git repos."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "setup-private" "" "Clone private git repos."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "setup-appuio" "" "Install and setup APPUiO OpenShift cli."
printf "| %-${cmd_width}s | %-${opt_width}s | %-${desc_width}s |\n" "version" "" "Show version of installed tools."

    echo
}

# Dynamic env vars

GIT_BRANCH=$(git symbolic-ref --short -q HEAD)

if command -v pacman >/dev/null 2>&1; then
    export PACKAGE_MANAGER="pacman"
elif command -v apt >/dev/null 2>&1; then
    export PACKAGE_MANAGER="apt"
else
    export PACKAGE_MANAGER="unknown"
fi

# Env commands

function init-venv() {
    if [ ! -d "venv$GIT_BRANCH" ]; then
        echo "Init venv$GIT_BRANCH with $(uv --version)."
        uv venv "venv$GIT_BRANCH"
    fi
}

function activate-venv() {
    echo "Source virtualenv venv$GIT_BRANCH."
    source "venv$GIT_BRANCH/bin/activate"
}

function version() {
    uv --version
    docker --version
    docker-compose --version
}

# Config commands

function enable-passwordless-sudo() {
    echo "Add user $USER to sudoers file."
    sudo sh -c "echo \"$USER	ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers.d/nopasswd"
}

# Install commands

function install-desktop() {
    echo "Install wcurl"
    curl -fLO https://raw.githubusercontent.com/curl/wcurl/main/wcurl
    chmod +x wcurl && sudo mv wcurl /usr/local/bin/wcurl

    echo "Install thunderbird"
    sudo apt install -y thunderbird

    echo "Install KeepassXC"
    sudo add-apt-repository ppa:phoerious/keepassxc
    sudo apt update && sudo apt install -y keepassxc

    echo "Install Nextcloud Desktop"
    sudo add-apt-repository ppa:xtradeb/apps
    sudo apt update && sudo apt install -y nextcloud-desktop

    echo "Install LibreWolf"
    sudo apt update && sudo apt install extrepo -y
    sudo extrepo enable librewolf
    sudo apt update && sudo apt install librewolf -y

    echo "Install Obsidian"
    wcurl https://github.com/obsidianmd/obsidian-releases/releases/download/v1.7.4/obsidian_1.7.4_amd64.deb
    sudo apt install -y ./obsidian_1.7.4_amd64.deb
    rm obsidian_1.7.4_amd64.deb
}

function install-docker() {
    echo "Install docker"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
        # https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

        # Add Docker's official GPG key:
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update

        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        sudo usermod -aG docker $USER
        newgrp docker

        echo  "Verify docker installation."
        docker run hello-world
    elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
        sudo pacman -S --noconfirm docker
    fi
}

function install-qemu() {
    echo "Install QEMU"
    sudo apt-get install -y qemu qemu-user-static binfmt-support

    echo "Copy docker config."
    sudo cp docker/daemon.json /etc/docker
    sudo systemctl restart docker
}

function install-fzf() {
    echo "Install fzf"
    [ ! -d "$HOME/.fzf" ] &&  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    yes | ~/.fzf/install
}

function install-podman() {
    echo "Install podman"
    sudo apt install -y podman

    echo "Add docker.io to search registry"
    sudo grep -qxF 'unqualified-search-registries = ["docker.io"]' /etc/containers/registries.conf || echo 'unqualified-search-registries = ["docker.io"]' | sudo tee -a /etc/containers/registries.conf
}

function install-kubectl() {
    echo "Install kubectl"
    # https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list 
    sudo apt-get update && sudo apt-get install -y kubectl
}

function install-kind() {
    install-kubectl
    
    echo "Install kind"
    # https://kind.sigs.k8s.io/docs/user/quick-start/#installation
    # For AMD64 / x86_64
    [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
    # For ARM64
    [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-arm64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind
}

function install-llm() {
    echo "Install LLM"
    uv tool install llm

    echo "Install deepseek models"
    llm install llm-deepseek
    echo "Set api key with: llm keys set deepseek"
}

function install-ollama() {
    echo "Install Ollama"
    curl -fsSL https://ollama.com/install.sh | sh
}

function install-exo() {
    echo "Install exo"
    curl -fsSL https://raw.githubusercontent.com/exoscale/cli/master/install-latest.sh | sh
}

function install-minikube() {
    install-kubectl

    echo "Install minikube"
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
}

function install-bin() {
    echo "Install binaries"
    sudo apt install -y jq htop xclip ripgrep bat
    sudo wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64 -O /usr/bin/yq &&\
    sudo chmod +x /usr/bin/yq
}

function install-vscodium() {
    echo "Install VSCodium"
    wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
        | gpg --dearmor \
        | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
    echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' \
        | sudo tee /etc/apt/sources.list.d/vscodium.list
    sudo apt update && sudo apt install -y codium
}

function install-python() {
    echo "Install uv"
    curl -LsSf https://astral.sh/uv/install.sh | sh
}

function install-node() {
    echo "Install node version manager"
    [ ! -d "$HOME/.nvm" ] && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

    echo "Install pnpm"
    curl -fsSL https://get.pnpm.io/install.sh | sh -

    echo "Install Node"
    source ~/.nvm/nvm.sh
    nvm install --lts
}

function install-pass() {
    echo "Install pass"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
         sudo apt install -y pass pass-extension-otp
    elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
        sudo pacman -S --noconfirm pass
    fi

    echo "Clone pass repo."
    [ ! -d "$HOME/.password-store" ] && git clone git@gitlab.com:janikvonrotz/pass.git ~/.password-store

    echo "Import gpg key with this command."
    echo "gpg --import /path/to/user@example.com.private.gpg"
}

function install-scripts() {
    echo "Copy bin/* to ~/bin/"
    mkdir -p ~/bin
    sudo cp -r bin/* ~/bin/
}

function install-tmux() {

    echo "Install tmux"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
        sudo apt install -y tmux
    elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
        sudo pacman -S --noconfirm zsh
    fi

    echo "Install tmux plugins"
    [ ! -d "$HOME/.tmux" ] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    echo "Copy tmux config."
    cp tmux/.tmux.conf ~

    echo "Source tmux config."
    tmux source ~/.tmux.conf

    echo "Open tmux and install plugins with: ctrl + b; shift + i"
}

function install-fish() {
    echo "Install fish"
    sudo apt install -y fish

    mkdir -p ~/.config/fish/completions

    echo "Copy fish config."
    cp fish/config.fish ~/.config/fish/config.fish

    echo "Copy fish completions."
    cp fish/completions/* ~/.config/fish/completions/
}

function install-vim() {
    echo "Install vim"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
        sudo apt install -y vim
    elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
        sudo pacman -S vim
    fi

    echo "Copy vimrc config."
    cp vim/.vimrc ~

    echo "Install vim plugins"
    vim -c ":PlugInstall"
}

function install-helix() {
    echo "Add helix ppa."
    sudo add-apt-repository ppa:maveonair/helix-editor
    sudo apt update

    echo "Install helix"
    sudo apt install -y helix

    echo "Copy vim keybindings."
    cp helix/config.toml ~/.config/helix/config.toml
}

function install-helm() {
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    sudo apt-get install apt-transport-https --yes
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt-get update
    sudo apt-get install helm
}

function install-nvim() {
    echo "Add neovim ppa."
    sudo add-apt-repository ppa:neovim-ppa/stable -y
    sudo apt update

    echo "Install neovim"
    sudo apt install -y neovim
}

function install-bash() {
    echo "Copy bash completions."
    sudo cp bash/completions/* /etc/bash_completion.d/

    echo "Copy bash aliases."
    sudo cp bash/.bash_aliases ~/.bash_aliases

    echo "Append bash runtime configuration."
    START_MARKER="# dotenv"
    END_MARKER="# dotenv end"
    sed -i "/$START_MARKER/,/$END_MARKER/d" ~/.bashrc
    {
        echo -e "\n$START_MARKER"
        cat bash/.bashrc
        echo "$END_MARKER"
    } >> ~/.bashrc
}

function install-zsh() {
    echo "Install zsh"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
        sudo apt install -y zsh
    elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
        sudo pacman -S --noconfirm zsh
    fi

    echo "Reset zsh."
    ZSH=

    echo "Remove oh-my-zsh folder."
    rm -rf ~/.oh-my-zsh

    echo "Set zsh custom."
    ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}
    cd ~

    echo "Install oh-my-zsh"
    curl -L https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh

    echo "Clone zsh autosuggestions."
    [ ! -d "$ZSH_CUSTOM/plugins/zsh-autosuggestions" ] && git clone https://github.com/zsh-users/zsh-autosuggestions "$ZSH_CUSTOM/plugins/zsh-autosuggestions"

    echo "Copy oh-my-zsh customizations."
    cp ~/dotfiles/oh-my-zsh/custom/*.zsh ~/.oh-my-zsh/custom

    echo "Copy oh-my-zsh completions."
    cp -r ~/dotfiles/oh-my-zsh/completions ~/.oh-my-zsh/completions

    echo "Set plugins list for zshrc."
    sed -i'' 's/plugins=.*/plugins=(ansible docker fzf git kubectl minikube podman)/g' ~/.zshrc

    echo "Set zsh default theme."
    sed -i'' 's/ZSH_THEME.*/ZSH_THEME="eastwood"/g' ~/.zshrc
}

function install-git() {
    echo "Copy git config."
    cp git/.gitconfig ~

    echo "Install GitHub cli"
    if [ "$PACKAGE_MANAGER" == "apt" ]; then
        (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install -y gh
    fi
}

# Uninstall commands

function uninstall-docker() {
    echo "Show install docker pages."
    dpkg -l | grep -i docker

    echo "Unistall docker"
    
    sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-ce-cli docker-compose-plugin
    sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce docker-compose-plugin

    sudo rm -rf /var/lib/docker /etc/docker
    sudo rm /etc/apparmor.d/docker
    sudo groupdel docker
    sudo rm -rf /var/run/docker.sock
    sudo rm -rf /var/lib/containerd
}

# Run commands

function run-open-webui() {
    DATA_DIR=~/.open-webui uvx --python 3.11 open-webui@latest serve
}

# Setup commands

function setup-steamdeck() {
    echo "If you have not already, use 'passwd' to create a password for the deck user."

    echo "Disable read-only mode"
    sudo steamos-readonly disable
    
    echo "Initialize the pacman keyring"
    sudo pacman-key --init

    echo "Populate the pacman keyring with the default Arch Linux keys"
    sudo pacman-key --populate archlinux holo

    echo "Try installing a package"
    sudo pacman -S vi
}

function setup-private() {
    echo "Pull janikvonrotz repos."
    [ ! -d "$HOME/knowledge" ] && git clone git@gitlab.com:janikvonrotz/knowlege ~/knowledge
    [ ! -d "$HOME/janikvonrotz.ch" ] && git clone git@github.com:janikvonrotz/janikvonrotz.ch ~/janikvonrotz.ch
    [ ! -d "$HOME/python.casa" ] && git clone git@github.com:janikvonrotz/python.casa ~/python.casa
    [ ! -d "$HOME/encrypt.casa" ] && git clone git@github.com:janikvonrotz/encrypt.casa ~/encrypt.casa
    [ ! -d "$HOME/.password-store" ] && git clone git@gitlab.com:janikvonrotz/pass.git ~/.password-store
}

function setup-mint-system() {
    echo "Pull Mint-System repos."
    [ ! -d "$HOME/Odoo-Build" ] && git clone git@github.com:Mint-System/Odoo-Build.git ~/Odoo-Build
    [ ! -d "$HOME/Odoo-Wiki" ] && git clone git@github.com:Mint-System/Odoo-Wiki.git ~/Odoo-Wiki
    [ ! -d "$HOME/Ansible-Build" ] && git clone git@github.com:Mint-System/Ansible-Build.git ~/Ansible-Build
    [ ! -d "$HOME/Ansible-Build/inventories" ] && git clone git@gitlab.com:Mint-System/Ansible-Inventories.git ~/Ansible-Build/inventories
    [ ! -d "$HOME/Wiki" ] && git clone git@github.com:Mint-System/Wiki.git ~/Wiki
    [ ! -d "$HOME/Website" ] && git clone git@github.com:Mint-System/Website.git ~/Website
    [ ! -d "$HOME/VarLog" ] && git clone git@github.com:Mint-System/VarLog.git ~/VarLog
}

function setup-sozialinfo() {
    echo "Pull Sozialinfo repos."
    [ ! -d "$HOME/Sozialinfo-Odoo-Build" ] && git clone git@github.com:Sozialinfo/Odoo-Build.git ~/Sozialinfo-Odoo-Build
    [ ! -d "$HOME/documentation" ] && git clone git@github.com:Sozialinfo/documentation.git ~/documentation
    [ ! -d "$HOME/Odoo-CD" ] && git clone git@github.com:Sozialinfo/Odoo-CD.git ~/Odoo-CD
    [ ! -d "$HOME/Odoo-CI" ] && git clone git@github.com:Sozialinfo/Odoo-CI.git ~/Odoo-CI
    [ ! -d "$HOME/Keycloak-CD" ] && git clone git@github.com:Sozialinfo/Keycloak-CD.git ~/Keycloak-CD
    [ ! -d "$HOME/sozialinfo-e2e" ] && git clone git@github.com:sozialinfo/sozialinfo-e2e.git ~/sozialinfo-e2e
    [ ! -d "$HOME/frontend" ] && git clone git@github.com:sozialinfo/sozialinfo-e2e.git ~/frontend
}

function setup-appuio() {
    ZONE=exoscale-ch-gva-2-0

    echo "Install OpenShift cli."
    wcurl https://downloads-openshift-console.apps.$ZONE.cloud/amd64/linux/oc.tar
    tar -xf oc.tar
    rm oc.tar
    mv oc ~/bin/oc

    echo "Get the login command of the $ZONE zone: https://oauth-openshift.apps.$ZONE.cloud/oauth/token/display"
}

if declare -f "$1" > /dev/null; then
    "$1" "${@:2}"
else
    echo "Unknown command: $1"
    help
    exit 1
fi
