#!/bin/bash

echo "Pull all git repos in $HOME."
REPOS=()
for REPO in $(find "$HOME" -maxdepth 2 -type d -name '.git'); do
    REPOS+=("$(basename "$(dirname "$REPO")")")
done
echo "Repos to pull: ${REPOS[*]}"

for REPO in $(find "$HOME" -maxdepth 2 -type d -name '.git'); do
    DIR=$(dirname "$REPO")
    echo "Pulling $(git -C "$DIR" branch --show-current) in $DIR"
    git -C "$DIR" pull
done